/**
 * BrassWater CMMS - Demo seed data
 * =================================
 * Realistic building maintenance data based on Quebec residential building
 * maintenance standards (Guide d'entretien pour les gestionnaires immobiliers).
 *
 * All data lives in-memory when DEMO_MODE is true.
 */

// ---------------------------------------------------------------------------
// Users
// ---------------------------------------------------------------------------

export const users = [
  {
    id: "usr-1",
    name: "Marc Lefebvre",
    email: "marc.lefebvre@brasswater.ca",
    role: "admin",
    avatarColor: "#3b82f6",
    title: "System Administrator",
  },
  {
    id: "usr-2",
    name: "Sophie Tremblay",
    email: "sophie.tremblay@brasswater.ca",
    role: "property_manager",
    avatarColor: "#8b5cf6",
    title: "Property Manager",
  },
  {
    id: "usr-3",
    name: "Jean-Pierre Dubois",
    email: "jp.dubois@brasswater.ca",
    role: "maintenance_staff",
    avatarColor: "#22c55e",
    title: "Maintenance Technician",
  },
  {
    id: "usr-4",
    name: "Isabelle Roy",
    email: "isabelle.roy@brasswater.ca",
    role: "inspector",
    avatarColor: "#f59e0b",
    title: "Building Inspector",
  },
];

// ---------------------------------------------------------------------------
// Buildings
// ---------------------------------------------------------------------------

export const buildings = [
  {
    id: "bld-1",
    name: "Résidence des Érables",
    address: "4500 Boulevard Saint-Laurent, Montréal, QC H2T 1R3",
    city: "Montréal",
    units: 120,
    floors: 12,
    yearBuilt: 2008,
    managerId: "usr-2",
    features: ["elevator", "pool", "sprinklers", "underground_parking", "gym"],
    imageUrl: null,
    totalArea: 14400,
    areaUnit: "m²",
  },
  {
    id: "bld-2",
    name: "Le Château Saint-Laurent",
    address: "250 Grande Allée Est, Québec, QC G1R 2H4",
    city: "Québec",
    units: 85,
    floors: 8,
    yearBuilt: 2015,
    managerId: "usr-2",
    features: ["elevator", "sprinklers", "underground_parking", "rooftop_terrace"],
    imageUrl: null,
    totalArea: 9200,
    areaUnit: "m²",
  },
  {
    id: "bld-3",
    name: "Domaine du Parc",
    address: "1800 Boulevard Le Corbusier, Laval, QC H7S 2K1",
    city: "Laval",
    units: 45,
    floors: 5,
    yearBuilt: 1998,
    managerId: "usr-2",
    features: ["elevator", "outdoor_parking", "storage_lockers"],
    imageUrl: null,
    totalArea: 5100,
    areaUnit: "m²",
  },
];

// ---------------------------------------------------------------------------
// Inspection Templates  (based on Quebec maintenance guide categories)
// ---------------------------------------------------------------------------

export const inspectionTemplates = [
  {
    id: "tpl-a10",
    categoryCode: "A10",
    categoryName: "Foundations",
    description: "Foundation, garage, and basement inspection covering structural integrity, waterproofing, and drainage systems.",
    frequency: "semi-annual",
    requiresContractor: false,
    requiresCertificate: false,
    applicableStandard: null,
    checklist: [
      { item: "Inspect concrete for cracks or spalling", category: "Structure" },
      { item: "Verify waterproofing membrane integrity", category: "Waterproofing" },
      { item: "Check for moisture infiltration or efflorescence", category: "Moisture" },
      { item: "Inspect exposed steel for corrosion", category: "Structure" },
      { item: "Examine wall coverings and coatings", category: "Finishes" },
      { item: "Test garage ventilation system", category: "Ventilation" },
      { item: "Inspect garage door operation and safety sensors", category: "Doors" },
      { item: "Verify sump pump operation and float switch", category: "Drainage" },
      { item: "Perform spring cleaning of drainage channels", category: "Drainage" },
    ],
  },
  {
    id: "tpl-b10",
    categoryCode: "B10",
    categoryName: "Interior Structure",
    description: "Interior structural elements including floors, walls, columns, and expansion joints.",
    frequency: "annual",
    requiresContractor: false,
    requiresCertificate: false,
    applicableStandard: null,
    checklist: [
      { item: "Check for floor movement or deflection", category: "Floors" },
      { item: "Inspect for structural deformation", category: "Structure" },
      { item: "Document cracks in wall and ceiling finishes", category: "Walls" },
      { item: "Look for delamination of surface materials", category: "Surfaces" },
      { item: "Check for humidity stains or water damage", category: "Moisture" },
      { item: "Inspect for mold growth or musty odors", category: "Air Quality" },
      { item: "Verify caulking around penetrations", category: "Sealing" },
      { item: "Document any visible prior repairs", category: "Documentation" },
      { item: "Inspect expansion joints for deterioration", category: "Joints" },
    ],
  },
  {
    id: "tpl-b20",
    categoryCode: "B20",
    categoryName: "Exterior Envelope / Facades",
    description: "Building envelope including masonry, cladding, windows, balconies, and attached elements. Subject to Loi 122 facade inspection every 5 years.",
    frequency: "semi-annual",
    requiresContractor: true,
    requiresCertificate: true,
    applicableStandard: "Loi 122 (Bill 122) - Facade safety inspection every 5 years",
    checklist: [
      { item: "Inspect mortar joints for cracks or erosion", category: "Masonry" },
      { item: "Check for brick bulging or displacement", category: "Masonry" },
      { item: "Examine exterior cladding attachment", category: "Cladding" },
      { item: "Document fissures or surface degradation", category: "Surface" },
      { item: "Inspect window glass for cracks or seal failure", category: "Windows" },
      { item: "Check curtain wall frames and gaskets", category: "Windows" },
      { item: "Verify sealant joints at transitions", category: "Sealing" },
      { item: "Inspect balcony slabs and waterproofing", category: "Balconies" },
      { item: "Test guardrail stability and anchorage", category: "Safety" },
      { item: "Inspect attached elements (signs, lights, anchors)", category: "Attachments" },
    ],
  },
  {
    id: "tpl-b30",
    categoryCode: "B30",
    categoryName: "Roofing",
    description: "Roof membrane, flashings, drains, and all rooftop mechanical penetrations.",
    frequency: "semi-annual",
    requiresContractor: true,
    requiresCertificate: false,
    applicableStandard: null,
    checklist: [
      { item: "Inspect membrane for degradation or blistering", category: "Membrane" },
      { item: "Check for material cracking or splitting", category: "Membrane" },
      { item: "Verify flashings are secure and sealed", category: "Flashings" },
      { item: "Clear blocked roof drains and scuppers", category: "Drainage" },
      { item: "Check for water accumulation (ponding)", category: "Drainage" },
      { item: "Remove vegetation growth on membrane", category: "Membrane" },
      { item: "Inspect sealing around mechanical box penetrations", category: "Penetrations" },
      { item: "Check for missing or damaged shingles", category: "Coverings" },
      { item: "Verify all unfixed elements are secured", category: "Safety" },
      { item: "Remove debris and clean roof surface", category: "Maintenance" },
    ],
  },
  {
    id: "tpl-c10",
    categoryCode: "C10",
    categoryName: "Interior Finishes",
    description: "Interior finishes in common areas including walls, ceilings, floors, stairs, and railings.",
    frequency: "annual",
    requiresContractor: false,
    requiresCertificate: false,
    applicableStandard: null,
    checklist: [
      { item: "Inspect wall and ceiling finishes for deterioration", category: "Walls/Ceilings" },
      { item: "Check for finish cracks or peeling paint", category: "Walls/Ceilings" },
      { item: "Look for discoloration or staining", category: "Walls/Ceilings" },
      { item: "Check for humidity damage or mold", category: "Air Quality" },
      { item: "Verify wall-mounted elements are secure", category: "Attachments" },
      { item: "Inspect floor coverings for damage or wear", category: "Floors" },
      { item: "Check baseboard condition and attachment", category: "Trim" },
      { item: "Inspect stair treads and nosings", category: "Stairs" },
      { item: "Test handrail stability", category: "Safety" },
      { item: "Verify guardrail height and spacing compliance", category: "Safety" },
    ],
  },
  {
    id: "tpl-d10",
    categoryCode: "D10",
    categoryName: "Elevators",
    description: "Elevator equipment, cab condition, and safety devices. Inspections range from weekly visual to quarterly professional.",
    frequency: "weekly/monthly/quarterly",
    requiresContractor: true,
    requiresCertificate: true,
    applicableStandard: "CAN/CSA-B44 Safety Code for Elevators",
    checklist: [
      { item: "Weekly: Verify cab lighting and ventilation", category: "Weekly" },
      { item: "Weekly: Check door operation and sensors", category: "Weekly" },
      { item: "Weekly: Test emergency phone/intercom", category: "Weekly" },
      { item: "Weekly: Inspect cab floor and walls for damage", category: "Weekly" },
      { item: "Monthly: Check leveling accuracy at each floor", category: "Monthly" },
      { item: "Monthly: Listen for unusual noises during travel", category: "Monthly" },
      { item: "Monthly: Inspect machine room temperature and cleanliness", category: "Monthly" },
      { item: "Quarterly: Professional maintenance by certified technician", category: "Quarterly" },
      { item: "Quarterly: Test emergency braking system", category: "Quarterly" },
      { item: "Quarterly: Inspect wire ropes or hydraulic cylinders", category: "Quarterly" },
    ],
  },
  {
    id: "tpl-d20",
    categoryCode: "D20",
    categoryName: "Plumbing",
    description: "Plumbing systems including water supply, hot water, pumps, drainage, and specialty equipment.",
    frequency: "weekly/monthly",
    requiresContractor: false,
    requiresCertificate: false,
    applicableStandard: null,
    checklist: [
      { item: "Verify main water valve accessibility and operation", category: "Water Supply" },
      { item: "Inspect boiler room for leaks or corrosion", category: "Heating" },
      { item: "Check hot water tank temperature and relief valve", category: "Hot Water" },
      { item: "Test circulating pumps and pressure gauges", category: "Pumps" },
      { item: "Verify glycol system concentration (if applicable)", category: "Heating" },
      { item: "Inspect kitchen equipment connections (commercial)", category: "Equipment" },
      { item: "Check gas appliance venting and connections", category: "Gas" },
      { item: "Verify sump pit and ejector pump operation", category: "Drainage" },
      { item: "Inspect grease trap and schedule cleaning", category: "Drainage" },
    ],
  },
  {
    id: "tpl-d30",
    categoryCode: "D30",
    categoryName: "HVAC",
    description: "Heating, ventilation, and air conditioning systems including rooftop units, air handlers, and exhaust fans.",
    frequency: "weekly/monthly/annual",
    requiresContractor: true,
    requiresCertificate: false,
    applicableStandard: null,
    checklist: [
      { item: "Check ventilation elements for proper airflow", category: "Ventilation" },
      { item: "Verify garage heating system operation", category: "Heating" },
      { item: "Inspect lobby and corridor heating", category: "Heating" },
      { item: "Replace filters and inspect belts (monthly)", category: "Maintenance" },
      { item: "Test kitchen exhaust ventilation", category: "Ventilation" },
      { item: "Inspect mechanical room for leaks or vibration", category: "Equipment" },
      { item: "Check compressor operation and refrigerant levels", category: "Cooling" },
      { item: "Inspect rooftop A/C units and condensate drains", category: "Cooling" },
      { item: "Test air exchangers and HRV units", category: "Ventilation" },
    ],
  },
  {
    id: "tpl-d40",
    categoryCode: "D40",
    categoryName: "Fire Protection",
    description: "Fire safety systems: sprinklers, alarms, extinguishers, emergency lighting, and smoke/heat detectors. The most detailed inspection category.",
    frequency: "weekly/monthly/quarterly/annual",
    requiresContractor: true,
    requiresCertificate: true,
    applicableStandard: "NFPA 25 / CAN/ULC-S536 / NFPA 72",
    checklist: [
      { item: "Weekly: Verify sprinkler control valves are open", category: "Weekly" },
      { item: "Weekly: Test emergency lighting operation", category: "Weekly" },
      { item: "Weekly: Check fire pump pressure gauges", category: "Weekly" },
      { item: "Monthly: Run fire pump test for 10 minutes", category: "Monthly" },
      { item: "Monthly: Test fire alarm panel and communicator", category: "Monthly" },
      { item: "Monthly: Verify fire department phone connection", category: "Monthly" },
      { item: "Quarterly: Inspect all portable fire extinguishers", category: "Quarterly" },
      { item: "Quarterly: Test smoke and heat detectors (sample)", category: "Quarterly" },
      { item: "Quarterly: Test manual pull stations (sample)", category: "Quarterly" },
      { item: "Annual: Full fire alarm system verification (CAN/ULC-S536)", category: "Annual" },
      { item: "Annual: Sprinkler system full inspection (NFPA 25)", category: "Annual" },
      { item: "Annual: Test fire door hold-open devices", category: "Annual" },
    ],
  },
  {
    id: "tpl-d50",
    categoryCode: "D50",
    categoryName: "Electrical",
    description: "Electrical systems, panels, emergency generators, and stairwell lighting.",
    frequency: "weekly",
    requiresContractor: true,
    requiresCertificate: true,
    applicableStandard: "CAN/CSA-C282 Emergency Generator",
    checklist: [
      { item: "Verify electrical room cleanliness and access", category: "Rooms" },
      { item: "Inspect panels for signs of overheating or damage", category: "Panels" },
      { item: "Check for signs of overheating on connections", category: "Safety" },
      { item: "Ensure electrical room ventilation is adequate", category: "Ventilation" },
      { item: "Test emergency stairwell lighting", category: "Emergency" },
      { item: "Generator: Check fuel level and top up", category: "Generator" },
      { item: "Generator: Verify oil and coolant levels", category: "Generator" },
      { item: "Generator: Inspect battery and charge level", category: "Generator" },
      { item: "Generator: Check belts and hoses", category: "Generator" },
      { item: "Generator: Verify alarm panel connection", category: "Generator" },
    ],
  },
  {
    id: "tpl-g20",
    categoryCode: "G20",
    categoryName: "Exterior / Landscaping",
    description: "Exterior grounds including parking, landscaping, lighting, fencing, and pedestrian surfaces.",
    frequency: "semi-annual",
    requiresContractor: false,
    requiresCertificate: false,
    applicableStandard: null,
    checklist: [
      { item: "Inspect parking surface for cracks and potholes", category: "Parking" },
      { item: "Verify signage and lane striping condition", category: "Parking" },
      { item: "Inspect trees for dead branches or disease", category: "Landscaping" },
      { item: "Check terrain grading and drainage", category: "Landscaping" },
      { item: "Inspect ponds, fountains, or water features", category: "Water Features" },
      { item: "Test exterior lighting fixtures and timers", category: "Lighting" },
      { item: "Inspect fencing and gates for damage", category: "Perimeter" },
      { item: "Check pedestrian surfaces for trip hazards", category: "Walkways" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Contractors
// ---------------------------------------------------------------------------

export const contractors = [
  {
    id: "ctr-1",
    name: "Sécurité Incendie Québec",
    specialty: "Fire Protection",
    phone: "(514) 555-0101",
    email: "info@siq-fire.ca",
    licenseNumber: "RBQ-5678-1234-01",
    status: "active",
    rating: 5,
    lastServiceDate: "2026-03-10",
  },
  {
    id: "ctr-2",
    name: "Ascenseurs Montréal Inc.",
    specialty: "Elevators",
    phone: "(514) 555-0202",
    email: "service@ascenseursmtl.ca",
    licenseNumber: "RBQ-4321-5678-02",
    status: "active",
    rating: 4,
    lastServiceDate: "2026-03-15",
  },
  {
    id: "ctr-3",
    name: "Plomberie Pro-Tec",
    specialty: "Plumbing",
    phone: "(450) 555-0303",
    email: "urgence@protec-plomberie.ca",
    licenseNumber: "RBQ-9876-5432-03",
    status: "active",
    rating: 4,
    lastServiceDate: "2026-02-28",
  },
  {
    id: "ctr-4",
    name: "Climatisation Nordique",
    specialty: "HVAC",
    phone: "(514) 555-0404",
    email: "service@climnordique.ca",
    licenseNumber: "RBQ-1122-3344-04",
    status: "active",
    rating: 3,
    lastServiceDate: "2026-03-05",
  },
  {
    id: "ctr-5",
    name: "Toitures Excellence",
    specialty: "Roofing",
    phone: "(418) 555-0505",
    email: "soumission@toitures-exc.ca",
    licenseNumber: "RBQ-5566-7788-05",
    status: "active",
    rating: 5,
    lastServiceDate: "2026-01-20",
  },
  {
    id: "ctr-6",
    name: "Électricité Savard",
    specialty: "Electrical",
    phone: "(450) 555-0606",
    email: "contact@elec-savard.ca",
    licenseNumber: "RBQ-2233-4455-06",
    status: "expired",
    rating: 3,
    lastServiceDate: "2025-11-15",
  },
];

// ---------------------------------------------------------------------------
// Work Orders
// ---------------------------------------------------------------------------

export const workOrders = [
  {
    id: "wo-1",
    title: "Emergency: Water leak in unit 405 ceiling",
    description: "Tenant reports active water dripping from living room ceiling. Possible pipe burst in unit 505 above. Immediate containment needed.",
    buildingId: "bld-1",
    type: "emergency",
    priority: 5,
    status: "in_progress",
    assigneeId: "usr-3",
    createdById: "usr-2",
    contractorId: "ctr-3",
    createdAt: "2026-03-23T08:15:00Z",
    updatedAt: "2026-03-23T09:30:00Z",
    estimatedCost: 2500,
    unit: "405",
  },
  {
    id: "wo-2",
    title: "Garage door motor replacement",
    description: "Main garage entrance door motor is intermittently failing. Door gets stuck at half-open position. Second occurrence this month.",
    buildingId: "bld-1",
    type: "priority",
    priority: 4,
    status: "approved",
    assigneeId: "usr-3",
    createdById: "usr-2",
    contractorId: null,
    createdAt: "2026-03-20T14:00:00Z",
    updatedAt: "2026-03-21T10:00:00Z",
    estimatedCost: 3200,
    unit: null,
  },
  {
    id: "wo-3",
    title: "Annual fire panel inspection",
    description: "Scheduled annual CAN/ULC-S536 fire alarm system verification. Contractor Sécurité Incendie Québec to perform full system test.",
    buildingId: "bld-2",
    type: "maintenance",
    priority: 3,
    status: "assigned",
    assigneeId: null,
    createdById: "usr-2",
    contractorId: "ctr-1",
    createdAt: "2026-03-18T09:00:00Z",
    updatedAt: "2026-03-19T11:00:00Z",
    estimatedCost: 4800,
    unit: null,
  },
  {
    id: "wo-4",
    title: "Lobby carpet replacement",
    description: "Main lobby carpet shows significant wear and staining. Replace with commercial-grade carpet tiles as per the approved renovation plan.",
    buildingId: "bld-1",
    type: "routine",
    priority: 2,
    status: "submitted",
    assigneeId: null,
    createdById: "usr-2",
    contractorId: null,
    createdAt: "2026-03-22T16:30:00Z",
    updatedAt: "2026-03-22T16:30:00Z",
    estimatedCost: 8500,
    unit: null,
  },
  {
    id: "wo-5",
    title: "Elevator vibration complaint - Unit 8B",
    description: "Resident in unit 8B reports excessive vibration and noise from elevator shaft. Possible guide rail misalignment. Contractor inspection required.",
    buildingId: "bld-2",
    type: "priority",
    priority: 4,
    status: "acknowledged",
    assigneeId: null,
    createdById: "usr-4",
    contractorId: "ctr-2",
    createdAt: "2026-03-21T11:45:00Z",
    updatedAt: "2026-03-22T08:00:00Z",
    estimatedCost: 1200,
    unit: "8B",
  },
  {
    id: "wo-6",
    title: "Replace broken window - 3rd floor corridor",
    description: "Corridor window on 3rd floor has a crack from thermal stress. Not an immediate safety issue but needs replacement before next winter.",
    buildingId: "bld-3",
    type: "routine",
    priority: 2,
    status: "approved",
    assigneeId: "usr-3",
    createdById: "usr-2",
    contractorId: null,
    createdAt: "2026-03-15T13:00:00Z",
    updatedAt: "2026-03-17T09:00:00Z",
    estimatedCost: 950,
    unit: null,
  },
  {
    id: "wo-7",
    title: "HVAC filter change - all units",
    description: "Quarterly HVAC filter replacement for all corridor and common area air handlers across the building.",
    buildingId: "bld-1",
    type: "maintenance",
    priority: 3,
    status: "completed",
    assigneeId: "usr-3",
    createdById: "usr-2",
    contractorId: "ctr-4",
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-03-08T16:00:00Z",
    estimatedCost: 1800,
    unit: null,
  },
  {
    id: "wo-8",
    title: "Parking lot crack sealing",
    description: "Multiple cracks in exterior parking lot surface require sealing before spring thaw causes further deterioration.",
    buildingId: "bld-3",
    type: "routine",
    priority: 2,
    status: "completed",
    assigneeId: "usr-3",
    createdById: "usr-2",
    contractorId: null,
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-03-05T14:30:00Z",
    estimatedCost: 3400,
    unit: null,
  },
  {
    id: "wo-9",
    title: "Generator fuel level low",
    description: "Weekly check revealed generator diesel tank below 50%. Schedule fuel delivery before next scheduled load test.",
    buildingId: "bld-1",
    type: "priority",
    priority: 4,
    status: "in_progress",
    assigneeId: "usr-3",
    createdById: "usr-3",
    contractorId: null,
    createdAt: "2026-03-22T07:30:00Z",
    updatedAt: "2026-03-23T08:00:00Z",
    estimatedCost: 600,
    unit: null,
  },
  {
    id: "wo-10",
    title: "Sprinkler valve #3 stuck",
    description: "During weekly valve check, sprinkler control valve #3 (zone 3, floors 4-6) found stuck in partially closed position. Requires immediate attention.",
    buildingId: "bld-1",
    type: "emergency",
    priority: 5,
    status: "completed",
    assigneeId: null,
    createdById: "usr-3",
    contractorId: "ctr-1",
    createdAt: "2026-03-19T06:45:00Z",
    updatedAt: "2026-03-19T14:00:00Z",
    estimatedCost: 750,
    unit: null,
  },
  {
    id: "wo-11",
    title: "Exterior light pole damaged",
    description: "Light pole near south entrance struck by snow plow. Pole is tilted and wiring may be exposed. Area cordoned off.",
    buildingId: "bld-3",
    type: "priority",
    priority: 4,
    status: "assigned",
    assigneeId: "usr-3",
    createdById: "usr-2",
    contractorId: "ctr-6",
    createdAt: "2026-03-16T15:00:00Z",
    updatedAt: "2026-03-17T08:30:00Z",
    estimatedCost: 2200,
    unit: null,
  },
  {
    id: "wo-12",
    title: "Grease trap cleaning overdue",
    description: "Grease trap in building commercial kitchen has not been cleaned in 3 months. Exceeds municipal bylaw maximum interval of 90 days.",
    buildingId: "bld-2",
    type: "maintenance",
    priority: 3,
    status: "acknowledged",
    assigneeId: null,
    createdById: "usr-4",
    contractorId: "ctr-3",
    createdAt: "2026-03-20T10:30:00Z",
    updatedAt: "2026-03-21T09:00:00Z",
    estimatedCost: 450,
    unit: null,
  },
  {
    id: "wo-13",
    title: "Roof drain blockage after storm",
    description: "Heavy rainstorm caused debris accumulation in two roof drains. Water ponding observed on northeast section of flat roof.",
    buildingId: "bld-2",
    type: "priority",
    priority: 4,
    status: "closed",
    assigneeId: "usr-3",
    createdById: "usr-3",
    contractorId: "ctr-5",
    createdAt: "2026-03-10T07:00:00Z",
    updatedAt: "2026-03-11T16:00:00Z",
    estimatedCost: 500,
    unit: null,
  },
  {
    id: "wo-14",
    title: "Pool pH level out of range",
    description: "Weekly water quality test shows pH at 8.2, above acceptable range. Chemical adjustment and retest required.",
    buildingId: "bld-1",
    type: "maintenance",
    priority: 3,
    status: "closed",
    assigneeId: "usr-3",
    createdById: "usr-3",
    createdAt: "2026-03-12T09:00:00Z",
    updatedAt: "2026-03-12T15:00:00Z",
    estimatedCost: 150,
    unit: null,
    contractorId: null,
  },
];

// ---------------------------------------------------------------------------
// Scheduled Inspections
// ---------------------------------------------------------------------------

export const scheduledInspections = [
  {
    id: "ins-1",
    templateId: "tpl-a10",
    buildingId: "bld-1",
    inspectorId: "usr-4",
    status: "completed",
    scheduledDate: "2026-02-15",
    completedDate: "2026-02-15",
    rating: 4,
    notes: "Minor hairline crack found in garage level B2 wall. Monitoring recommended. All sump pumps operational.",
  },
  {
    id: "ins-2",
    templateId: "tpl-b20",
    buildingId: "bld-1",
    inspectorId: "usr-4",
    status: "completed",
    scheduledDate: "2026-02-20",
    completedDate: "2026-02-21",
    rating: 3,
    notes: "Several mortar joints on north facade showing erosion. Balcony sealant on floors 8-10 needs replacement within 6 months. Guardrails secure.",
  },
  {
    id: "ins-3",
    templateId: "tpl-b30",
    buildingId: "bld-2",
    inspectorId: "usr-4",
    status: "completed",
    scheduledDate: "2026-02-25",
    completedDate: "2026-02-25",
    rating: 5,
    notes: "Roof membrane in excellent condition. All drains clear. Flashings secure. No ponding observed.",
  },
  {
    id: "ins-4",
    templateId: "tpl-d40",
    buildingId: "bld-1",
    inspectorId: "usr-4",
    status: "completed",
    scheduledDate: "2026-03-01",
    completedDate: "2026-03-01",
    rating: 4,
    notes: "All fire safety systems operational. One emergency light on floor 6 had dead battery - replaced on site. Sprinkler valve #3 slightly stiff, work order created.",
  },
  {
    id: "ins-5",
    templateId: "tpl-d10",
    buildingId: "bld-2",
    inspectorId: null,
    status: "scheduled",
    scheduledDate: "2026-03-25",
    completedDate: null,
    rating: null,
    notes: null,
  },
  {
    id: "ins-6",
    templateId: "tpl-d50",
    buildingId: "bld-1",
    inspectorId: "usr-3",
    status: "completed",
    scheduledDate: "2026-03-05",
    completedDate: "2026-03-05",
    rating: 4,
    notes: "Electrical rooms clean and accessible. Generator fuel at 48% - work order created for fuel delivery. Battery charge normal.",
  },
  {
    id: "ins-7",
    templateId: "tpl-c10",
    buildingId: "bld-3",
    inspectorId: "usr-4",
    status: "completed",
    scheduledDate: "2026-03-08",
    completedDate: "2026-03-08",
    rating: 2,
    notes: "Significant wear on 3rd and 4th floor corridor carpets. Water stain on 2nd floor ceiling near stairwell - possible roof leak above. Handrails on stairwell B loose.",
  },
  {
    id: "ins-8",
    templateId: "tpl-d20",
    buildingId: "bld-1",
    inspectorId: "usr-3",
    status: "completed",
    scheduledDate: "2026-03-10",
    completedDate: "2026-03-10",
    rating: 3,
    notes: "Hot water tank #2 showing early corrosion at base. Grease trap needs cleaning. All pumps operational. Main valve accessible.",
  },
  {
    id: "ins-9",
    templateId: "tpl-d30",
    buildingId: "bld-1",
    inspectorId: null,
    status: "scheduled",
    scheduledDate: "2026-03-28",
    completedDate: null,
    rating: null,
    notes: null,
  },
  {
    id: "ins-10",
    templateId: "tpl-g20",
    buildingId: "bld-3",
    inspectorId: "usr-4",
    status: "overdue",
    scheduledDate: "2026-03-15",
    completedDate: null,
    rating: null,
    notes: null,
  },
  {
    id: "ins-11",
    templateId: "tpl-b10",
    buildingId: "bld-2",
    inspectorId: "usr-4",
    status: "scheduled",
    scheduledDate: "2026-04-01",
    completedDate: null,
    rating: null,
    notes: null,
  },
  {
    id: "ins-12",
    templateId: "tpl-d40",
    buildingId: "bld-2",
    inspectorId: null,
    status: "scheduled",
    scheduledDate: "2026-04-05",
    completedDate: null,
    rating: null,
    notes: null,
  },
  {
    id: "ins-13",
    templateId: "tpl-a10",
    buildingId: "bld-3",
    inspectorId: "usr-4",
    status: "in_progress",
    scheduledDate: "2026-03-22",
    completedDate: null,
    rating: null,
    notes: "Started inspection. Garage level complete, moving to basement areas.",
  },
  {
    id: "ins-14",
    templateId: "tpl-d40",
    buildingId: "bld-3",
    inspectorId: "usr-4",
    status: "overdue",
    scheduledDate: "2026-03-10",
    completedDate: null,
    rating: null,
    notes: null,
  },
  {
    id: "ins-15",
    templateId: "tpl-b20",
    buildingId: "bld-2",
    inspectorId: null,
    status: "scheduled",
    scheduledDate: "2026-04-10",
    completedDate: null,
    rating: null,
    notes: null,
  },
  {
    id: "ins-16",
    templateId: "tpl-d50",
    buildingId: "bld-3",
    inspectorId: "usr-3",
    status: "completed",
    scheduledDate: "2026-03-12",
    completedDate: "2026-03-12",
    rating: 3,
    notes: "Generator battery showing signs of age. Recommend replacement within 2 months. All panels in order.",
  },
];

// ---------------------------------------------------------------------------
// Compliance Requirements
// ---------------------------------------------------------------------------

export const complianceRequirements = [
  {
    id: "comp-1",
    buildingId: "bld-1",
    name: "Loi 122 Facade Inspection",
    standard: "Bill 122 / RBQ",
    frequency: "5 years",
    lastInspectionDate: "2023-06-15",
    nextDueDate: "2028-06-15",
    status: "compliant",
    notes: "Last inspection by engineer firm Groupe-ABS. Report on file.",
  },
  {
    id: "comp-2",
    buildingId: "bld-1",
    name: "NFPA 25 Sprinkler Inspection",
    standard: "NFPA 25",
    frequency: "annual",
    lastInspectionDate: "2025-09-20",
    nextDueDate: "2026-09-20",
    status: "compliant",
    notes: "Performed by Sécurité Incendie Québec. All systems pass.",
  },
  {
    id: "comp-3",
    buildingId: "bld-1",
    name: "CAN/ULC-S536 Fire Alarm Verification",
    standard: "CAN/ULC-S536",
    frequency: "annual",
    lastInspectionDate: "2025-11-10",
    nextDueDate: "2026-11-10",
    status: "compliant",
    notes: "Full system verification completed. Certificate issued.",
  },
  {
    id: "comp-4",
    buildingId: "bld-1",
    name: "CAN/CSA-C282 Emergency Generator",
    standard: "CAN/CSA-C282",
    frequency: "semi-annual",
    lastInspectionDate: "2025-12-01",
    nextDueDate: "2026-06-01",
    status: "due_soon",
    notes: "Next test due in June. Schedule with electrical contractor.",
  },
  {
    id: "comp-5",
    buildingId: "bld-1",
    name: "Elevator Safety Certificate",
    standard: "CAN/CSA-B44",
    frequency: "annual",
    lastInspectionDate: "2025-08-15",
    nextDueDate: "2026-08-15",
    status: "compliant",
    notes: "Certificate valid until August 2026.",
  },
  {
    id: "comp-6",
    buildingId: "bld-1",
    name: "Pool Water Quality",
    standard: "MAPAQ / Municipal Bylaw",
    frequency: "weekly",
    lastInspectionDate: "2026-03-21",
    nextDueDate: "2026-03-28",
    status: "compliant",
    notes: "Weekly testing on schedule. pH corrected on March 12.",
  },
  {
    id: "comp-7",
    buildingId: "bld-2",
    name: "Loi 122 Facade Inspection",
    standard: "Bill 122 / RBQ",
    frequency: "5 years",
    lastInspectionDate: "2021-04-20",
    nextDueDate: "2026-04-20",
    status: "due_soon",
    notes: "Due next month. Engineering firm must be retained.",
  },
  {
    id: "comp-8",
    buildingId: "bld-2",
    name: "NFPA 25 Sprinkler Inspection",
    standard: "NFPA 25",
    frequency: "annual",
    lastInspectionDate: "2025-07-10",
    nextDueDate: "2026-07-10",
    status: "compliant",
    notes: "Annual inspection completed. Minor deficiency corrected on site.",
  },
  {
    id: "comp-9",
    buildingId: "bld-2",
    name: "CAN/ULC-S536 Fire Alarm Verification",
    standard: "CAN/ULC-S536",
    frequency: "annual",
    lastInspectionDate: "2025-05-22",
    nextDueDate: "2026-05-22",
    status: "due_soon",
    notes: "Due in May. Sécurité Incendie Québec contacted for scheduling.",
  },
  {
    id: "comp-10",
    buildingId: "bld-2",
    name: "Elevator Safety Certificate",
    standard: "CAN/CSA-B44",
    frequency: "annual",
    lastInspectionDate: "2025-10-05",
    nextDueDate: "2026-10-05",
    status: "compliant",
    notes: "Certificate on file. Next renewal October 2026.",
  },
  {
    id: "comp-11",
    buildingId: "bld-3",
    name: "Loi 122 Facade Inspection",
    standard: "Bill 122 / RBQ",
    frequency: "5 years",
    lastInspectionDate: "2020-03-10",
    nextDueDate: "2025-03-10",
    status: "non_compliant",
    notes: "OVERDUE - Inspection was due March 2025. Must schedule immediately. Potential fine from RBQ.",
  },
  {
    id: "comp-12",
    buildingId: "bld-3",
    name: "NFPA 20 Fire Pump Test",
    standard: "NFPA 20",
    frequency: "annual",
    lastInspectionDate: "2025-04-15",
    nextDueDate: "2026-04-15",
    status: "due_soon",
    notes: "Annual flow test due next month.",
  },
  {
    id: "comp-13",
    buildingId: "bld-3",
    name: "CAN/ULC-S536 Fire Alarm Verification",
    standard: "CAN/ULC-S536",
    frequency: "annual",
    lastInspectionDate: "2025-01-20",
    nextDueDate: "2026-01-20",
    status: "overdue",
    notes: "OVERDUE since January. Contractor scheduling delayed. Urgent.",
  },
  {
    id: "comp-14",
    buildingId: "bld-3",
    name: "Elevator Safety Certificate",
    standard: "CAN/CSA-B44",
    frequency: "annual",
    lastInspectionDate: "2025-06-30",
    nextDueDate: "2026-06-30",
    status: "compliant",
    notes: "Valid until June 2026.",
  },
];

// ---------------------------------------------------------------------------
// Activity Log
// ---------------------------------------------------------------------------

export const activityLog = [
  {
    id: "act-1",
    type: "inspection_completed",
    message: "Completed foundation inspection at Résidence des Érables",
    userId: "usr-4",
    buildingId: "bld-1",
    relatedId: "ins-1",
    timestamp: "2026-02-15T16:30:00Z",
  },
  {
    id: "act-2",
    type: "inspection_completed",
    message: "Completed facade inspection at Résidence des Érables - deficiencies noted",
    userId: "usr-4",
    buildingId: "bld-1",
    relatedId: "ins-2",
    timestamp: "2026-02-21T15:00:00Z",
  },
  {
    id: "act-3",
    type: "inspection_completed",
    message: "Completed roofing inspection at Le Château Saint-Laurent - all clear",
    userId: "usr-4",
    buildingId: "bld-2",
    relatedId: "ins-3",
    timestamp: "2026-02-25T14:45:00Z",
  },
  {
    id: "act-4",
    type: "inspection_completed",
    message: "Completed fire protection inspection at Résidence des Érables",
    userId: "usr-4",
    buildingId: "bld-1",
    relatedId: "ins-4",
    timestamp: "2026-03-01T17:00:00Z",
  },
  {
    id: "act-5",
    type: "work_order_created",
    message: "Created work order: Parking lot crack sealing",
    userId: "usr-2",
    buildingId: "bld-3",
    relatedId: "wo-8",
    timestamp: "2026-02-25T10:00:00Z",
  },
  {
    id: "act-6",
    type: "work_order_completed",
    message: "Completed work order: HVAC filter change - all units",
    userId: "usr-3",
    buildingId: "bld-1",
    relatedId: "wo-7",
    timestamp: "2026-03-08T16:00:00Z",
  },
  {
    id: "act-7",
    type: "inspection_completed",
    message: "Completed electrical inspection at Résidence des Érables",
    userId: "usr-3",
    buildingId: "bld-1",
    relatedId: "ins-6",
    timestamp: "2026-03-05T15:30:00Z",
  },
  {
    id: "act-8",
    type: "work_order_completed",
    message: "Completed work order: Parking lot crack sealing",
    userId: "usr-3",
    buildingId: "bld-3",
    relatedId: "wo-8",
    timestamp: "2026-03-05T14:30:00Z",
  },
  {
    id: "act-9",
    type: "inspection_completed",
    message: "Completed interior finishes inspection at Domaine du Parc - poor condition noted",
    userId: "usr-4",
    buildingId: "bld-3",
    relatedId: "ins-7",
    timestamp: "2026-03-08T17:00:00Z",
  },
  {
    id: "act-10",
    type: "inspection_completed",
    message: "Completed plumbing inspection at Résidence des Érables",
    userId: "usr-3",
    buildingId: "bld-1",
    relatedId: "ins-8",
    timestamp: "2026-03-10T16:00:00Z",
  },
  {
    id: "act-11",
    type: "work_order_created",
    message: "Created work order: Roof drain blockage after storm",
    userId: "usr-3",
    buildingId: "bld-2",
    relatedId: "wo-13",
    timestamp: "2026-03-10T07:00:00Z",
  },
  {
    id: "act-12",
    type: "work_order_completed",
    message: "Completed work order: Roof drain blockage after storm",
    userId: "usr-3",
    buildingId: "bld-2",
    relatedId: "wo-13",
    timestamp: "2026-03-11T16:00:00Z",
  },
  {
    id: "act-13",
    type: "work_order_completed",
    message: "Completed work order: Pool pH level out of range",
    userId: "usr-3",
    buildingId: "bld-1",
    relatedId: "wo-14",
    timestamp: "2026-03-12T15:00:00Z",
  },
  {
    id: "act-14",
    type: "inspection_completed",
    message: "Completed electrical inspection at Domaine du Parc",
    userId: "usr-3",
    buildingId: "bld-3",
    relatedId: "ins-16",
    timestamp: "2026-03-12T16:30:00Z",
  },
  {
    id: "act-15",
    type: "work_order_created",
    message: "Created work order: Replace broken window - 3rd floor corridor",
    userId: "usr-2",
    buildingId: "bld-3",
    relatedId: "wo-6",
    timestamp: "2026-03-15T13:00:00Z",
  },
  {
    id: "act-16",
    type: "work_order_created",
    message: "Created work order: Exterior light pole damaged",
    userId: "usr-2",
    buildingId: "bld-3",
    relatedId: "wo-11",
    timestamp: "2026-03-16T15:00:00Z",
  },
  {
    id: "act-17",
    type: "compliance_updated",
    message: "Updated compliance status: CAN/ULC-S536 at Domaine du Parc marked overdue",
    userId: "usr-2",
    buildingId: "bld-3",
    relatedId: "comp-13",
    timestamp: "2026-03-18T09:00:00Z",
  },
  {
    id: "act-18",
    type: "work_order_completed",
    message: "Completed work order: Sprinkler valve #3 stuck - valve freed and tested",
    userId: "usr-3",
    buildingId: "bld-1",
    relatedId: "wo-10",
    timestamp: "2026-03-19T14:00:00Z",
  },
  {
    id: "act-19",
    type: "work_order_created",
    message: "Created work order: Grease trap cleaning overdue",
    userId: "usr-4",
    buildingId: "bld-2",
    relatedId: "wo-12",
    timestamp: "2026-03-20T10:30:00Z",
  },
  {
    id: "act-20",
    type: "work_order_created",
    message: "Created work order: Elevator vibration complaint - Unit 8B",
    userId: "usr-4",
    buildingId: "bld-2",
    relatedId: "wo-5",
    timestamp: "2026-03-21T11:45:00Z",
  },
  {
    id: "act-21",
    type: "inspection_started",
    message: "Started foundation inspection at Domaine du Parc",
    userId: "usr-4",
    buildingId: "bld-3",
    relatedId: "ins-13",
    timestamp: "2026-03-22T09:00:00Z",
  },
  {
    id: "act-22",
    type: "work_order_created",
    message: "Created work order: Generator fuel level low",
    userId: "usr-3",
    buildingId: "bld-1",
    relatedId: "wo-9",
    timestamp: "2026-03-22T07:30:00Z",
  },
  {
    id: "act-23",
    type: "work_order_created",
    message: "Created work order: Lobby carpet replacement",
    userId: "usr-2",
    buildingId: "bld-1",
    relatedId: "wo-4",
    timestamp: "2026-03-22T16:30:00Z",
  },
  {
    id: "act-24",
    type: "work_order_created",
    message: "Created emergency work order: Water leak in unit 405 ceiling",
    userId: "usr-2",
    buildingId: "bld-1",
    relatedId: "wo-1",
    timestamp: "2026-03-23T08:15:00Z",
  },
];

// ---------------------------------------------------------------------------
// Inventory — Asset Check-in / Check-out System
// ---------------------------------------------------------------------------

export const inventoryCategories = [
  { id: "cat-tools", name: "Power Tools", color: "#3b82f6" },
  { id: "cat-hand", name: "Hand Tools", color: "#06b6d4" },
  { id: "cat-safety", name: "Safety Equipment", color: "#ef4444" },
  { id: "cat-testing", name: "Testing & Meters", color: "#f59e0b" },
  { id: "cat-access", name: "Access Equipment", color: "#10b981" },
  { id: "cat-cleaning", name: "Cleaning Equipment", color: "#8b5cf6" },
  { id: "cat-keys", name: "Keys & Access Cards", color: "#64748b" },
];

export const inventoryItems = [
  // Power Tools
  { id: "inv-1", name: "DeWalt Hammer Drill DCD996", assetTag: "PT-001", category: "cat-tools", status: "checked_out", condition: "good", unitCost: 329.00, lastLocation: "bld-1", checkedOutBy: "usr-3", checkedOutDate: "2026-03-22T08:30:00Z", notes: "20V MAX XR, for concrete anchoring work in garage." },
  { id: "inv-2", name: "Milwaukee Reciprocating Saw", assetTag: "PT-002", category: "cat-tools", status: "available", condition: "good", unitCost: 249.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "M18 FUEL SAWZALL. Keep blade stock in tool room." },
  { id: "inv-3", name: "Makita Angle Grinder 4.5\"", assetTag: "PT-003", category: "cat-tools", status: "checked_out", condition: "fair", unitCost: 189.00, lastLocation: "bld-3", checkedOutBy: "usr-4", checkedOutDate: "2026-03-21T14:00:00Z", notes: "Needs new guard. Ordered replacement." },
  { id: "inv-4", name: "Bosch Rotary Laser Level", assetTag: "PT-004", category: "cat-tools", status: "available", condition: "good", unitCost: 599.00, lastLocation: "bld-2", checkedOutBy: null, checkedOutDate: null, notes: "Self-leveling, for alignment work." },
  { id: "inv-5", name: "DeWalt Portable Table Saw", assetTag: "PT-005", category: "cat-tools", status: "maintenance", condition: "needs_repair", unitCost: 449.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "Blade guard mechanism jammed. Sent for service Mar 18." },
  // Hand Tools
  { id: "inv-6", name: "Ridgid Pipe Wrench Set (14\"/18\"/24\")", assetTag: "HT-001", category: "cat-hand", status: "checked_out", condition: "good", unitCost: 145.00, lastLocation: "bld-2", checkedOutBy: "usr-3", checkedOutDate: "2026-03-23T07:00:00Z", notes: "Heavy duty aluminum set." },
  { id: "inv-7", name: "Klein Electrician Tool Kit", assetTag: "HT-002", category: "cat-hand", status: "available", condition: "good", unitCost: 210.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "11-piece insulated set, 1000V rated." },
  { id: "inv-8", name: "Knipex Pliers Set", assetTag: "HT-003", category: "cat-hand", status: "available", condition: "good", unitCost: 175.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "Cobra, Lineman, and Needle-nose." },
  { id: "inv-9", name: "Stanley Socket Set 200pc", assetTag: "HT-004", category: "cat-hand", status: "checked_out", condition: "good", unitCost: 189.00, lastLocation: "bld-1", checkedOutBy: "usr-4", checkedOutDate: "2026-03-20T09:15:00Z", notes: "SAE and metric, 1/4\" 3/8\" 1/2\" drive." },
  // Safety Equipment
  { id: "inv-10", name: "3M Full-Face Respirator 6800", assetTag: "SE-001", category: "cat-safety", status: "available", condition: "good", unitCost: 165.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "Medium size. P100 cartridges in cabinet." },
  { id: "inv-11", name: "Miller Fall Protection Harness", assetTag: "SE-002", category: "cat-safety", status: "checked_out", condition: "good", unitCost: 285.00, lastLocation: "bld-1", checkedOutBy: "usr-3", checkedOutDate: "2026-03-22T08:30:00Z", notes: "Annual inspection due Jun 2026." },
  { id: "inv-12", name: "Confined Space Gas Monitor", assetTag: "SE-003", category: "cat-safety", status: "available", condition: "good", unitCost: 750.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "4-gas (O2/LEL/CO/H2S). Calibration due Apr 2026." },
  { id: "inv-13", name: "Miller Fall Protection Harness #2", assetTag: "SE-004", category: "cat-safety", status: "retired", condition: "needs_repair", unitCost: 285.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "RETIRED - Failed annual inspection. Webbing frayed. Replaced by SE-002." },
  // Testing & Meters
  { id: "inv-14", name: "Fluke 87V Digital Multimeter", assetTag: "TM-001", category: "cat-testing", status: "checked_out", condition: "good", unitCost: 425.00, lastLocation: "bld-2", checkedOutBy: "usr-4", checkedOutDate: "2026-03-23T10:00:00Z", notes: "True RMS. For electrical panel inspection." },
  { id: "inv-15", name: "FLIR C5 Thermal Camera", assetTag: "TM-002", category: "cat-testing", status: "available", condition: "good", unitCost: 699.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "For detecting heat loss, water leaks, electrical hotspots." },
  { id: "inv-16", name: "Extech Moisture Meter", assetTag: "TM-003", category: "cat-testing", status: "available", condition: "good", unitCost: 89.00, lastLocation: "bld-3", checkedOutBy: null, checkedOutDate: null, notes: "Pin-type for drywall and concrete moisture." },
  // Access Equipment
  { id: "inv-17", name: "Werner 28ft Extension Ladder", assetTag: "AE-001", category: "cat-access", status: "checked_out", condition: "good", unitCost: 389.00, lastLocation: "bld-3", checkedOutBy: "usr-3", checkedOutDate: "2026-03-21T11:00:00Z", notes: "Fiberglass, 300lb capacity. For exterior facade work." },
  { id: "inv-18", name: "Little Giant Multi-Position Ladder", assetTag: "AE-002", category: "cat-access", status: "available", condition: "good", unitCost: 299.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "22ft reach. For interior common area work." },
  { id: "inv-19", name: "Scaffold Tower 6ft Platform", assetTag: "AE-003", category: "cat-access", status: "maintenance", condition: "fair", unitCost: 850.00, lastLocation: "bld-2", checkedOutBy: null, checkedOutDate: null, notes: "Wheels need replacement. Parts on order." },
  // Cleaning Equipment
  { id: "inv-20", name: "Kärcher Pressure Washer K5", assetTag: "CE-001", category: "cat-cleaning", status: "available", condition: "good", unitCost: 449.00, lastLocation: "bld-1", checkedOutBy: null, checkedOutDate: null, notes: "2000 PSI. For garage and exterior cleaning." },
  { id: "inv-21", name: "Tennant Floor Scrubber T300", assetTag: "CE-002", category: "cat-cleaning", status: "checked_out", condition: "good", unitCost: 3200.00, lastLocation: "bld-1", checkedOutBy: "usr-3", checkedOutDate: "2026-03-24T06:30:00Z", notes: "Walk-behind, for garage spring cleaning." },
  // Keys & Access Cards
  { id: "inv-22", name: "Master Key Set - Résidence des Érables", assetTag: "KY-001", category: "cat-keys", status: "checked_out", condition: "good", unitCost: 0, lastLocation: "bld-1", checkedOutBy: "usr-3", checkedOutDate: "2026-03-24T07:00:00Z", notes: "All common areas + mechanical rooms. Sign-out required." },
  { id: "inv-23", name: "Master Key Set - Le Château Saint-Laurent", assetTag: "KY-002", category: "cat-keys", status: "available", condition: "good", unitCost: 0, lastLocation: "bld-2", checkedOutBy: null, checkedOutDate: null, notes: "Stored in secure lockbox, office." },
  { id: "inv-24", name: "Elevator Machine Room Access Card", assetTag: "KY-003", category: "cat-keys", status: "checked_out", condition: "good", unitCost: 0, lastLocation: "bld-2", checkedOutBy: "usr-4", checkedOutDate: "2026-03-23T10:00:00Z", notes: "Programmed for all 3 buildings. Return after shift." },
];

export const checkoutHistory = [
  { id: "ch-1", itemId: "inv-1", action: "checkout", userId: "usr-3", date: "2026-03-22T08:30:00Z", notes: "For garage anchor bolt installation" },
  { id: "ch-2", itemId: "inv-3", action: "checkout", userId: "usr-4", date: "2026-03-21T14:00:00Z", notes: "Cutting rebar for balcony repair" },
  { id: "ch-3", itemId: "inv-6", action: "checkout", userId: "usr-3", date: "2026-03-23T07:00:00Z", notes: "Plumbing repair unit 302" },
  { id: "ch-4", itemId: "inv-9", action: "checkout", userId: "usr-4", date: "2026-03-20T09:15:00Z", notes: "Elevator mechanical room work" },
  { id: "ch-5", itemId: "inv-11", action: "checkout", userId: "usr-3", date: "2026-03-22T08:30:00Z", notes: "Roof anchor inspection" },
  { id: "ch-6", itemId: "inv-14", action: "checkout", userId: "usr-4", date: "2026-03-23T10:00:00Z", notes: "Panel voltage check, bld-2 main" },
  { id: "ch-7", itemId: "inv-17", action: "checkout", userId: "usr-3", date: "2026-03-21T11:00:00Z", notes: "Facade sealant inspection access" },
  { id: "ch-8", itemId: "inv-21", action: "checkout", userId: "usr-3", date: "2026-03-24T06:30:00Z", notes: "Garage spring deep clean" },
  { id: "ch-9", itemId: "inv-22", action: "checkout", userId: "usr-3", date: "2026-03-24T07:00:00Z", notes: "Morning shift" },
  { id: "ch-10", itemId: "inv-24", action: "checkout", userId: "usr-4", date: "2026-03-23T10:00:00Z", notes: "Elevator inspection" },
  { id: "ch-11", itemId: "inv-15", action: "checkin", userId: "usr-4", date: "2026-03-21T16:00:00Z", notes: "Done - found heat leak in unit 812 window" },
  { id: "ch-12", itemId: "inv-2", action: "checkin", userId: "usr-3", date: "2026-03-20T15:30:00Z", notes: "Pipe cut complete, returned to tool room" },
  { id: "ch-13", itemId: "inv-7", action: "checkin", userId: "usr-4", date: "2026-03-19T17:00:00Z", notes: "Panel rewiring done in bld-1 lobby" },
  { id: "ch-14", itemId: "inv-20", action: "checkin", userId: "usr-3", date: "2026-03-18T14:00:00Z", notes: "Garage entrance cleaned" },
];
